# Generated by Django 5.1.4 on 2025-07-17 23:53

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.event_banner_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_flyer',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_flyer_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.payment_qr_upload_path),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.speaker_profile_upload_path),
        ),
    ]
