# Generated by Django 5.1.4 on 2025-07-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
    ]
