# Generated by Django 5.1.4 on 2025-07-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_payment_instructions_event_payment_qr_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
