# Generated by Django 5.1.4 on 2025-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateopportunity',
            name='credit_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of credit hours if available (e.g., 3.0)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='certificateopportunity',
            name='credits_available',
            field=models.BooleanField(default=False, help_text='Whether credits can be claimed for this certification'),
        ),
    ]
