# Generated by Django 5.1.4 on 2025-07-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_certificateopportunity_credit_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateopportunity',
            name='credits_available',
        ),
        migrations.AlterField(
            model_name='certificateopportunity',
            name='credit_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of credit hours if university credit is available (e.g., 3.0)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='certificateopportunity',
            name='university_credit',
            field=models.BooleanField(default=False, help_text='Whether this certification provides university credit'),
        ),
    ]
