# Generated by Django 5.1.4 on 2025-07-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_certificateopportunity_internshipopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateopportunity',
            name='percentage_offer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage if any (e.g., 20.00 for 20% off)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificateopportunity',
            name='validity_till',
            field=models.DateTimeField(blank=True, help_text='Validity date for the offer/course', null=True),
        ),
    ]
