# Generated by Django 5.2.4 on 2025-07-05 15:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('scheme', models.PositiveIntegerField(help_text='e.g., 2019, 2021')),
                ('year_of_joining', models.PositiveIntegerField(help_text='e.g., 2021')),
                ('expected_year_of_passout', models.PositiveIntegerField(help_text='e.g., 2025')),
                ('ongoing_semester', models.PositiveIntegerField(help_text='Current semester (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('year_of_study', models.PositiveIntegerField(help_text='Year of study (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheme', 'year_of_joining', 'full_name'],
                'indexes': [models.Index(fields=['scheme', 'year_of_joining'], name='students_st_scheme_554062_idx'), models.Index(fields=['ongoing_semester'], name='students_st_ongoing_0d5719_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.PositiveIntegerField()),
                ('year_of_joining', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('scheme', 'year_of_joining', 'is_active')},
            },
        ),
    ]
