# Generated by Django 5.1.4 on 2025-07-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='current_salary_range',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(default='Electronics Engineering', editable=False, max_length=100),
        ),
    ]
