# Generated by Django 5.1.4 on 2025-07-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_remove_alumni_current_salary_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnievent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='alumnieventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='alumnieventregistration',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='current_designation',
        ),
        migrations.AddField(
            model_name='alumni',
            name='job_title',
            field=models.CharField(blank=True, help_text='Current job title or designation', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='scheme',
            field=models.PositiveIntegerField(blank=True, help_text='Academic scheme year (e.g., 2019, 2021)', null=True),
        ),
        migrations.DeleteModel(
            name='AlumniCSVUpload',
        ),
        migrations.DeleteModel(
            name='AlumniEvent',
        ),
        migrations.DeleteModel(
            name='AlumniEventRegistration',
        ),
    ]
