# Generated by Django 5.2.4 on 2025-07-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App'), ('machine_learning', 'Machine Learning'), ('iot', 'Internet of Things'), ('robotics', 'Robotics'), ('embedded_systems', 'Embedded Systems'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('ai', 'Artificial Intelligence'), ('other', 'Other')], max_length=30)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Frontend Developer, UI Designer', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_220446_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by'], name='projects_pr_created_c24ee1_idx'),
        ),
    ]
