# Generated by Django 5.1.4 on 2025-07-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(blank=True, help_text='Project abstract or summary', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_report',
            field=models.FileField(blank=True, help_text='Upload project report (PDF)', null=True, upload_to='project_reports/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload project image', upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as main project image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['-is_featured', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='YouTube, Vimeo, or direct video URL')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as main project video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project')),
            ],
            options={
                'ordering': ['-is_featured', 'created_at'],
            },
        ),
    ]
