# Generated by Django 5.1.4 on 2025-07-17 23:53

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_images',
            field=models.ImageField(blank=True, help_text='Project screenshots or images', null=True, upload_to=projects.models.project_image_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_report',
            field=models.FileField(blank=True, help_text='Upload project report (PDF)', null=True, upload_to=projects.models.project_report_upload_path),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Upload project image', upload_to=projects.models.project_gallery_upload_path),
        ),
    ]
