# Generated by Django 5.1.4 on 2025-07-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student_names',
        ),
    ]
