# Generated by Django 5.1.4 on 2025-07-14 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_abstract_project_project_report_projectimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this project on homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Make this project visible to public'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_images',
            field=models.ImageField(blank=True, help_text='Project screenshots or images', null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='student_batch',
            field=models.CharField(blank=True, help_text='e.g., 2021-2025', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='student_department',
            field=models.CharField(default='Electronics Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='student_names',
            field=models.TextField(blank=True, help_text='Names of students who worked on this project', null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'is_published'], name='projects_pr_is_feat_7f1332_idx'),
        ),
    ]
