version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eesa_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_NAME=eesa_backend
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_PORT=5432
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles

volumes:
  postgres_data:
