services:
  # Django Web Service
  - type: web
    name: eesa-college-portal
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn eesa_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: eesa-postgres
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.com"
        
  # PostgreSQL Database
  - type: pgsql
    name: eesa-postgres
    plan: free
    databaseName: eesa_db
    user: eesa_user
