# Generated by Django 5.1.4 on 2025-07-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
