# Generated by Django 5.1.4 on 2025-07-17 23:53

import placements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=placements.models.company_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='placementapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=placements.models.resume_upload_path),
        ),
    ]
