# Generated by Django 5.1.4 on 2025-07-14 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('roll_number', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('batch_year', models.IntegerField(help_text='Graduation year')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('job_title', models.CharField(max_length=200)),
                ('package_lpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_details', models.TextField(blank=True, help_text='Additional package details')),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=50)),
                ('offer_date', models.DateField()),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='placement_offers/')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='placed_students/')),
                ('testimonial', models.TextField(blank=True, help_text='Student testimonial about placement')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by placement coordinator')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_students', to='placements.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placement_drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placements.placementdrive')),
            ],
            options={
                'ordering': ['-offer_date', '-package_lpa'],
                'unique_together': {('student_email', 'company', 'offer_date')},
            },
        ),
    ]
