# Generated by Django 5.1.4 on 2025-07-18 12:20

import django.db.models.deletion
import placements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_alter_company_logo_alter_placementapplication_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedstudent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='placementcoordinator',
            name='department',
        ),
        migrations.CreateModel(
            name='PlacementBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brochure title or description', max_length=200)),
                ('file', models.FileField(help_text='Placement brochure PDF or document', upload_to=placements.models.placement_brochure_upload_path)),
                ('description', models.TextField(blank=True, help_text='Additional information about the brochure')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=9)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current/active brochure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='placements.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'academic_year')},
            },
        ),
    ]
