# Generated by Django 5.1.4 on 2025-07-18 12:25

import placements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_remove_placedstudent_branch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placementbrochure',
            unique_together={('academic_year',)},
        ),
        migrations.AlterField(
            model_name='placementbrochure',
            name='file',
            field=models.FileField(help_text='Department placement brochure PDF or document', upload_to=placements.models.placement_brochure_upload_path),
        ),
        migrations.RemoveField(
            model_name='placementbrochure',
            name='company',
        ),
    ]
