# Generated by Django 5.1.4 on 2025-07-18 13:31

import django.db.models.deletion
import placements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_alter_placementbrochure_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementdrive',
            name='eligible_branches',
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='application_link',
            field=models.URLField(default='https://example.com/apply', help_text='Link for students to apply for this placement drive'),
        ),
        migrations.CreateModel(
            name='StudentCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Placement Coordinator', max_length=100)),
                ('profile_picture', models.ImageField(help_text="Upload coordinator's profile picture", upload_to=placements.models.student_coordinator_image_upload_path)),
                ('mobile_number', models.CharField(help_text='Contact mobile number', max_length=15)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('bio', models.TextField(blank=True, help_text='Brief bio or description')),
                ('is_active', models.BooleanField(default=True, help_text='Show in public listings')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_coordinator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Coordinator',
                'verbose_name_plural': 'Student Coordinators',
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
        migrations.DeleteModel(
            name='PlacementCoordinator',
        ),
    ]
