# Generated by Django 5.1.4 on 2025-07-17 23:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.team_member_upload_path),
        ),
    ]
