# Generated by Django 5.1.4 on 2025-07-18 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teammember_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
