# Generated by Django 5.1.4 on 2025-07-06 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='module_number',
            field=models.PositiveIntegerField(choices=[(1, 'Module 1'), (2, 'Module 2'), (3, 'Module 3'), (4, 'Module 4'), (5, 'Module 5'), (0, 'Other/General')], default=1, help_text='Module number (1-5) or 0 for general'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('module', 'Module Notes'), ('pyq', 'Previous Year Questions'), ('textbook', 'Textbook'), ('other', 'Other')], default='module', max_length=20),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['note_type', 'module_number'], name='academics_n_note_ty_ba9858_idx'),
        ),
    ]
