# Generated by Django 5.2.4 on 2025-07-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['scheme', 'semester'], name='academics_s_scheme_e4d5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academics_s_code_3689e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'scheme', 'semester')},
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['subject', 'is_approved'], name='academics_n_subject_779264_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['uploaded_by'], name='academics_n_uploade_d8f123_idx'),
        ),
    ]
