# Generated by Django 5.1.4 on 2025-07-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academiccategory_academicresource_resourcedownload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Academic Categories'},
        ),
    ]
