# Generated by Django 5.1.4 on 2025-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_create_fixed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicresource',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('internal', 'Internal Exam'), ('sem', 'Semester Exam'), ('other', 'Other')], help_text='Exam type for PYQ', max_length=20),
        ),
    ]
